title: Theme Test
description: Keith's Test Repo
theme: jekyll-theme-cayman
github.is_project_page: false

# emote_theme: pages-themes/minima@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
